# -*- coding: utf-8 -*-
"""DS_final2_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SPf1WcHFh5-F7nFB7MZN2bXQPsvJ_xaS
"""

import joblib
import numpy as np
import streamlit as st

model = joblib.load('gradient_boosting_model.pkl')
scaler = joblib.load('scaler.pkl')

st.title("Solar Power Generation Predictor")
st.write("Enter the features to predict power generation.")

distance_to_solar_noon = st.number_input("Distance to Solar Noon", min_value=0)
temperature = st.number_input("Temperature",min_value=0)
wind_direction = st.number_input("Wind Direction",min_value=0)
wind_speed = st.number_input("Wind Speed",min_value=0)


features = np.array([[distance_to_solar_noon, temperature, wind_direction, wind_speed]])

if st.button("Predict"):
    features = np.array([[distance_to_solar_noon, temperature, wind_direction, wind_speed]])
    features_scaled = scaler.transform(features)
    prediction = model.predict(features_scaled)
    st.write(f"Predicted Power Generation: {prediction[0]}")